SMETS2.Request.Web/Models/ErrorViewModel.cs
namespace SMETS2.Request.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SMETS2.Request.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SMETS2.Request.Web.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Hosting;

namespace SMETS2.Request.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> logger;
        private readonly IWebHostEnvironment env;

        public HomeController(ILogger<HomeController> logger, IWebHostEnvironment env)
        {
            this.logger = logger;
            this.env = env;
        }

        public IActionResult Index()
        {
            ViewBag.environmentName = env.EnvironmentName;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SMETS2.Request.Web/Controllers/RequestTrackingController.cs
using Microsoft.AspNetCore.Mvc;
using SMETS2.Req.ClassLibrary.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using SMETS2.Req.ClassLibrary.Models;

namespace SMETS2.Request.Web.Controllers
{
    public class RequestTrackingController : Controller
    {
        private readonly IRequestTrackingRepository requestTrackingRepository;
        private readonly IWebHostEnvironment env;

        public RequestTrackingController(IRequestTrackingRepository requestTrackingRepository, IWebHostEnvironment env)
        {
            this.requestTrackingRepository = requestTrackingRepository;
            this.env = env;
        }

        // GET: RequestTracking
        public IActionResult Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            ViewBag.environmentName = env.EnvironmentName;

            ViewData["CurrentSort"] = sortOrder;
            ViewData["RequestReferenceDateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_asc" : "";
            ViewData["RequestReferenceSortParm"] = sortOrder == "ref" ? "ref_desc" : "ref";
            ViewData["RequestGuidSortParm"] = sortOrder == "guid" ? "guid_desc" : "guid";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            IEnumerable<RequestTracking> requestTrackings = requestTrackingRepository.GetAll();

            //IEnumerable<RequestTracking> requestTrackings =
            //    requestTrackings0.OrderByDescending(r => r.RequestReferenceDate).Take(10000); 


            if (!String.IsNullOrEmpty(searchString))
            {
                requestTrackings = requestTrackings.Where(s => s.RequestReference == searchString
                                                               || s.RequestGuid == searchString);
            }

            switch (sortOrder)
            {
                case "date_asc":
                    requestTrackings = requestTrackings.OrderBy(s => s.RequestReferenceDate);
                    break;
                case "ref":
                    requestTrackings = requestTrackings.OrderBy(s => s.RequestReference);
                    break;
                case "ref_desc":
                    requestTrackings = requestTrackings.OrderByDescending(s => s.RequestReference);
                    break;
                case "guid":
                    requestTrackings = requestTrackings.OrderBy(s => s.RequestGuid);
                    break;
                case "guid_desc":
                    requestTrackings = requestTrackings.OrderByDescending(s => s.RequestGuid);
                    break;
                default:
                    requestTrackings = requestTrackings.OrderByDescending(s => s.RequestReferenceDate);
                    break;
            }

            int pageSize = 10;
            return View(PaginatedList<RequestTracking>.Create(requestTrackings.AsQueryable(), pageNumber ?? 1, pageSize));

            //return View(requestTrackings.ToList());
        }

        // GET: RequestTracking/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestTracking = requestTrackingRepository.Get(id);
            if (requestTracking == null)
            {
                return NotFound();
            }
            return View(requestTracking);
        }

        // GET: RequestTracking/Create
        [NonAction]
        public ActionResult Create()
        {
            return View();
        }

        // POST: RequestTracking/Create/5
        [NonAction]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RequestTracking requestTracking)
        {
            if (ModelState.IsValid)
            {
                requestTrackingRepository.Create(requestTracking);
                return RedirectToAction(nameof(Index));
            }
            return View(requestTracking);
        }

        // GET: RequestTracking/Edit/5
        [NonAction]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestTracking = requestTrackingRepository.Get(id);
            if (requestTracking == null)
            {
                return NotFound();
            }
            return View(requestTracking);
        }

        // POST: RequestTracking/Edit/5
        [NonAction]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, RequestTracking requestTracking)
        {
            if (id != requestTracking.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                requestTrackingRepository.Update(id, requestTracking);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(requestTracking);
            }
        }

        // GET: RequestTracking/Delete/5
        [NonAction]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestTracking = requestTrackingRepository.Get(id);
            if (requestTracking == null)
            {
                return NotFound();
            }
            return View(requestTracking);
        }

        // POST: RequestTracking/Delete/5
        [NonAction]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                var requestTracking = requestTrackingRepository.Get(id);

                if (requestTracking == null)
                {
                    return NotFound();
                }

                requestTrackingRepository.Delete(requestTracking.Id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SMETS2.Request.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = ViewBag.environmentName + " SMETS2 Request Tracking";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the</h1>
    <h1 class="display-4">@ViewBag.environmentName</h1>
    <h1 class="display-4">SMETS2 Request Tracking Application</h1>
    <p>Select any of the links at the top</p>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>

SMETS2.Request.Web/Views/RequestTracking/Create.cshtml
@model SMETS2.Req.ClassLibrary.Models.RequestTracking

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Request Tracking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RequestGuid" class="control-label"></label>
                <input asp-for="RequestGuid" class="form-control" />
                <span asp-validation-for="RequestGuid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestReference" class="control-label"></label>
                <input asp-for="RequestReference" class="form-control" />
                <span asp-validation-for="RequestReference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestReferenceDate" class="control-label"></label>
                <input asp-for="RequestReferenceDate" class="form-control" />
                <span asp-validation-for="RequestReferenceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestUrl" class="control-label"></label>
                <input asp-for="RequestUrl" class="form-control" />
                <span asp-validation-for="RequestUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/custom-validation.js"></script>
}

SMETS2.Request.Web/Views/RequestTracking/Delete.cshtml
@model SMETS2.Req.ClassLibrary.Models.RequestTracking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request Tracking</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestGuid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestGuid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestReference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestReference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestReferenceDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestReferenceDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SMETS2.Request.Web/Views/RequestTracking/Details.cshtml
@model SMETS2.Req.ClassLibrary.Models.RequestTracking

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Request Tracking</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestGuid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestGuid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestReference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestReference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestReferenceDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestReferenceDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestUrl)
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    <a asp-action="Index">Back to List</a>
</div>

SMETS2.Request.Web/Views/RequestTracking/Edit.cshtml
@model SMETS2.Req.ClassLibrary.Models.RequestTracking

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Request Tracking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RequestGuid" class="control-label"></label>
                <input asp-for="RequestGuid" class="form-control" />
                <span asp-validation-for="RequestGuid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestReference" class="control-label"></label>
                <input asp-for="RequestReference" class="form-control" />
                <span asp-validation-for="RequestReference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestReferenceDate" class="control-label"></label>
                <input asp-for="RequestReferenceDate" class="form-control" />
                <span asp-validation-for="RequestReferenceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestUrl" class="control-label"></label>
                <input asp-for="RequestUrl" class="form-control" />
                <span asp-validation-for="RequestUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/custom-validation.js"></script>
}

SMETS2.Request.Web/Views/RequestTracking/Index.cshtml
@model PaginatedList<SMETS2.Req.ClassLibrary.Models.RequestTracking>
@*using IEnumerable<SMETS2.Req.ClassLibrary.Models.RequestTracking>*@

@{ ViewData["Title"] = ViewBag.environmentName + " - Request Tracking"; }

<h1>@ViewBag.environmentName - Request Tracking</h1>

@*<p>
    <a asp-action="Create">Create New Route</a>
</p>*@
<br />

<form asp-action="Index" method="get">

    <div class="form-row">
        <div class="col-4">
            <input type="text" class="form-control" name="SearchString" placeholder="Enter RequestGuid or RequestReference" value="@ViewData["CurrentFilter"]">
        </div>
        <div class="col">
            <button type="submit" class="btn btn-primary mb-2">Search</button> |
            <a asp-action="Index">Back to Full List</a>
        </div>

    </div>
</form>

<br />

<table class="table table-striped">
    <thead>
    <tr>
        <th>
            <a asp-action="Index" asp-route-sortOrder="@ViewData["RequestGuidSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">RequestGuid</a>
            @*<a asp-action="Index" asp-route-sortOrder="@ViewData["RequestGuidSortParm"]">@Html.DisplayNameFor(model => model.RequestGuid)</a>*@
            @*@Html.DisplayNameFor(model => model.RequestGuid)*@
        </th>
        <th>
            <a asp-action="Index" asp-route-sortOrder="@ViewData["RequestReferenceSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">RequestReference</a>
            @*<a asp-action="Index" asp-route-sortOrder="@ViewData["RequestReferenceSortParm"]">@Html.DisplayNameFor(model => model.RequestReference)</a>*@
            @*@Html.DisplayNameFor(model => model.RequestReference)*@
        </th>
        <th>
            <a asp-action="Index" asp-route-sortOrder="@ViewData["RequestReferenceDateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">RequestReferenceDate</a>
            @*<a asp-action="Index" asp-route-sortOrder="@ViewData["RequestReferenceDateSortParm"]">@Html.DisplayNameFor(model => model.RequestReferenceDate)</a>*@
            @*@Html.DisplayNameFor(model => model.RequestReferenceDate)*@
        </th>
        <th>
            RequestUrl
            @*@Html.DisplayNameFor(model => model.RequestUrl)*@
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RequestGuid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequestReference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequestReferenceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequestUrl)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |*@
                @Html.ActionLink("Details", "Details", new { id = item.Id }) @*|*@
                @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
            </td>
        </tr>
    }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-primary @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-primary @nextDisabled">
    Next
</a>

SMETS2.Request.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMETS2 Request Tracking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        $(document).ready(function () {
            $("h1:contains('Development')").each(function () {
                $(this).html($(this).html().replace("Development", "<span class='green'>Development</span>"));
            });

            $("h1:contains('Production')").each(function () {
                $(this).html($(this).html().replace("Production", "<span class='red'>Production</span>"));
            });
        });
    </script>
    
    <style>

        .red {
            color: red;
        }

        .green {
            color: green;
        }

        .navbar .navbar-brand img {
            height: 50px;
        }

        * {
            margin: 0;
            padding: 0;
        }

        .imgbox {
            display: grid;
            height: 100%;
        }

        .center-fit {
            max-width: 100%;
            max-height: 100vh;
            margin: auto;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="~/images/utilita-energy-limited-vector-logo.png" title="SMETS2 Request Tracking" alt="SMETS2 Request Tracking" />
                </a>
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SMETS2 Request Tracking</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RequestTracking" asp-action="Index">RequestTracking</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Utilita Energy Limited
            <script type="text/javascript">
                document.write(new Date().getFullYear());
            </script>
            - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>